### ISSUE TITLE
Get vertical-collection ready for v1.0.0

### ISSUE THREAD

**Issue by pzuraq** [html-next/vertical-collection#1]
Here's the shortlist of the things we need for this to be ready for v1.0.0:

- [x] accessibility
  - [x] renderEverything switch
  - [ ] ensure focus updates correctly on scroll
- [ ] Documentation
  - [ ] More examples in general
  - [ ] Better coverage of the API docs
  - [ ] Table quirks (@runspired will also blog about this)
- [x] Rollup -private (@runspired thinks this should yield ~50% reduction in file size)
- [x] Improve debug Visualization performance
- [x] Fastboot
  - [x] granular control for fastboot (can be moved post 1.0 if significant refactoring needed)
- [x] ~Tests. All kinds of tests. For everything. Mostly should be integration tests, unit tests can follow when the internals are more solidified.~
  - [x] ~Tests with RecordArrays~
  - [x] ~Tests with ArrayProxies~
  - [x] ~Tests with PromiseArrays~  
  - [x] ~Tests with normal arrays~
  - [x] ~Tests with `Ember.A()` arrays~
- [x] ~Yield to inverse logic. Should yield when items is empty~
- [x] ~Resizing logic. Whenever we resize the scroll container, we need to update the VCs and rerender.~
- [x] ~Yield `heightDidChange` action for when height changes on an already rendered item~

**Comment by runspired** [comment]
@pzuraq added a few tasks.

**Comment by runspired** [comment]
Some notes on performance and other things (not all of these need to be addressed for 1.0, but many should be)

- [ ] resize needs to be more properly debounced
- [ ] our scheduling redefines two functions that have meaningful work every single time, we should extract to a stable function to reduce allocation cost
- [ ] we aren’t using all our queues, lets drop what we don’t need
- [ ] the forced layout on initial render costs p90 from 100ms to 300ms
- [ ] our calls into measure in radar vs dynamic radar should probably be made together not separate
- [ ] we should not allocate queue arrays until they are needed
- [ ] `SkipList` could be a ton faster, it’s allocations are overly aggressive
- [ ] we hit infinite recursion when resizing the page to be larger within `insertRangeBefore`
- [ ] we seem to be getting math wrong occasionally when starting in non-zero scroll offsets (may be related to the resize issue)
- [ ] some of our getters are zalgo, and others are unnecessary, we should audit and reduce our footprint if possible

**Comment by pzuraq** [comment]
Marked notes that I think have been addressed since your last comment was made, let me know if I'm wrong

**Comment by nolman** [comment]
I'm curious what the table quirks are @runspired 

I'm seeing some odd jiggle/resize behavior with ember table's tables that I believe is caused by the <occluded-content> element that vertical collection creates.

**Comment by v3ss0n** [comment]
how is this project going? Development stopped?

**Comment by pzuraq** [comment]
At the moment, yes. @runspired and I are both very busy working on Ember/Ember Data, so we don't really have time to work on this 😕

The reality is though that the current version of this addon will likely ship as v1.0.0, there isn't much more we _can_ do to make this better for older versions of Ember, aside from fixing a few outstanding bugs and adding documentation. We have some ideas for how we can use newer Ember APIs in v2/v3 to make this project much better, and in the long run I think we want to actually get low-level integration into the Glimmer VM so that recycling can be way more efficient. There are a lot of other things we need to focus on first though in Ember, so it'll likely be a while before we're able to tackle v2 of vertical-collection.

**Comment by mixonic** [comment]
1.0 happened!

**Comment by v3ss0n** [comment]
Unfortunately we have moved away from Emberjs  , would be nice if this avalbiel to others like Vue and Svelte  .
