### ISSUE TITLE
Turn off vertical collection debug message

### ISSUE THREAD

**Issue by patocallaghan** [html-next/vertical-collection#100]
Just wondering if would you entertain a PR to add the ability to switch off the vertical collection debug message in the console? We try to keep our app console free of unnecessary debugging messages and deprecation warnings and would love to turn off the vertical-collection one if we could. We currently see it in `dev` and `test`.

https://github.com/html-next/vertical-collection/blob/6f19fcb64a220f7ee19dbaa6efffc72bd6829472/index.js#L142

If so, should it appear based off of a flag?

**Comment by pzuraq** [comment]
I think we can probably remove them outright for now, and add instrumentation back in with Heimdall/ember-perf-timeline. What do you think @runspired

**Comment by patocallaghan** [comment]
@pzuraq I was actually just referring to the console message below but you guys know best :)

```
===================================================================
	Vertical Collection
	:: Including CSS for Visual Debugger
	:: (included in non production builds only)
	:: To use, set {{#vertical-collection debug=true}}
	:: To debug your applied CSS rules, set {{#vertical-collection debugCSS=true}}
===================================================================
```

**Comment by pzuraq** [comment]
Ah for sure, thought you meant the web console 😅 I think it would be fine to remove that or at least make it more minimal, we just need to update the documentation to let people know about it. I want to hear @runspired's thoughts first though

**Comment by runspired** [comment]
I think we should just remove this in favor of documenting the aggressive code stripping etc. we do in production that we don't do in dev. I added that initially because at the time no addons were considering how to minimize their prod footprint, but these days many do.

**Comment by patocallaghan** [comment]
I just noticed you removed this. Thanks 🙌 

any idea when the next beta release is?

**Comment by pzuraq** [comment]
Working on it now, I'd like to get 3 new features in, the optional rectcling PR (just needs tests) and two a11y features

**Comment by pzuraq** [comment]
@patocallaghan beta 5 is up!
