### ISSUE TITLE
Add mouseenter/mouseleave events

### ISSUE THREAD

**Issue by cibernox** [html-next/vertical-collection#118]
It's not clear to me what is the idiomatic way of adding `mouseevent/mouseleave` events on each entry of the collection. Using event delegation is not easy because those events don't bubble.

**Comment by pzuraq** [comment]
I'd think adding them to a component directly would be the best way:

```
{{#vertical-collection items as |item|}}
  {{component-with-mouse-events item=item}}
{{/vertical-collection}}
```

Is there something that's preventing you from doing that?

**Comment by runspired** [comment]
@cibernox could you explain why you think they don't bubble or provide a twiddle?

**Comment by pzuraq** [comment]
I'm closing this for now to cleanup the issue tracker. Let us know if you're still having issues setting up mouse events! The goal is to have everything work as if VC didn't exist at all, so they should be bubbling correctly.
