### ISSUE TITLE
VC does not detect table body height change.

### ISSUE THREAD

**Issue by billy-addepar** [html-next/vertical-collection#127]
My table is using VC and only 2 rows are rendered at the beginning:

<img width="1043" alt="screen shot 2017-08-26 at 2 07 22 pm" src="https://user-images.githubusercontent.com/11281370/29745111-e94f3660-8a67-11e7-8c57-b9e7ed8884c9.png">

You can see entire white space below the first 2 rows. However, as you start scrolling all other rows start to render.
<img width="1036" alt="screen shot 2017-08-26 at 2 08 28 pm" src="https://user-images.githubusercontent.com/11281370/29745118-0e5cedd0-8a68-11e7-8c7a-1ee8880f1b89.png">

To reproduce this:
- Checkout my branch https://github.com/billy-addepar/vertical-collection/tree/billy/table-reproduction
- Go to route http://localhost:4200/#/examples/table

This happens because in the first RAF execution, the table only measures the header and the body height is 0. VC detects 0 container height and only renders 2 items. However, as the body has something inside, the table body expands to its full height leaving entire blank space below 2 rows. This is not a resize event. VC does not detect change in body height and does not update accordingly. 

When you start scrolling, the VC sees the new container height and renders all rows as expected. All these events could be observed by putting a debugger in the radar. 

Note that this only happens for my table since I have some special CSS applied to table. (check app.css). 

Not sure how to fix this as I cannot find an easy way to detect change in table body height.

**Comment by pzuraq** [comment]
I think this may be more of a CSS/timing issue, the container should be able to know it's height by the first render frame somehow. As a temporary fix, consider using initialRenderCount to fill out the first render.

**Comment by billy-addepar** [comment]
That sounds a good idea. The only issue with that is `initialRenderCount` is used very early in the construction of VC component
https://github.com/html-next/vertical-collection/blob/master/addon/-private/data-view/radar/radar.js#L67

At that time, we do not have everything rendered on screen yet. Nor do we know the height of table. Hence it's very hard to know what `initialRenderCount` value should be

**Comment by billy-addepar** [comment]
I should we should consider moving some variables initialization in `init` of `radar` to the first RAF. At that time the parent component of the VC has some knowledge of surrounding environment and can give more accurate estimate of `bufferSize`, `initialRenderCount`, `estimateHeight`, etc.

**Comment by pzuraq** [comment]
initialRenderCount is not supposed to be accurate, it just allows you to render something on the very first render. We don't have enough information to render the correct number until the first paint (first RAF), and in some cases we never have that information (fastboot) so it's essentially a guess.

By first the time VC is running in the first paint, everything we need to know the correct number of items should be there. All CSS has been calculated, so actual item heights are known. This issue indicates that something changes _after_ that first paint, but it's hard to know what without diving in and I'm about to head into the mountains so gunna have trouble with that till next week 😛

So long term solution. We make sure VC always renders last so it knows the correct item height. Short term solution, give it an initial number as a guess (whatever you think should render if the user was using fastboot)

**Comment by billy-addepar** [comment]
There is an issue with calculating `max-height` in VC. If `max-height` is a percentage, its number is not calculated correctly. This PR fixes that:

https://github.com/html-next/vertical-collection/pull/128

**Comment by pzuraq** [comment]
Fixed by #128
