### ISSUE TITLE
Add ability to insert block above or below scrollable content

### ISSUE THREAD

**Issue by erichonkanen** [html-next/vertical-collection#131]
Hello,

I have a use case where I want to insert a block of content  at the very beginning of a collection (index 0 AND at very beginning of results e.g. no next link), the way I had thought to do this was a simple block inside the block form of vertical-collection but it seems there is no `yield` in the template to make this possible.

Could we add such a capability? Example:

```
{{#vertical-collection
    items
    as |item index section|}}
  {{#if (and isAtBeginning (eq section 'above') (eq index 0))}}
    <h1>Yay we are at the very beginning!</h1>
  {{/if}}
  ...
{{/vertical-collection}}
```

component/template
```
{{yield 'above'}}

{{#each virtualComponents key="id" as |virtualComponent index| ~}}
  {{~unbound virtualComponent.upperBound~}}
  {{~#if virtualComponent.element ~}}
    {{{unbound virtualComponent.element}}}
  {{~else~}}
    {{~yield virtualComponent.content virtualComponent.index ~}}
  {{~/if~}}
  {{~unbound virtualComponent.lowerBound~}}
{{~/each}}

{{yield 'below'}}

{{#if shouldYieldToInverse}}
  {{yield to="inverse"}}
{{/if}}
```

**Comment by pzuraq** [comment]
If I understand what you're trying to do, it should actually be doable currently without modifying `vertical-collection`. The collection is designed to not need to be the only child of the scroll container, so a header or footer can exist in the same scroll container and it should adapt accordingly:

```
<div class="scroll-container">
  <h1>Yay we are at the very beginning!</h1>
  {{#vertical-collection items as |item index|}}
    ...
  {{/vertical-collection}}
  <h1>Yay we are at the very end!</h1>
</div>
```

Does that do what you're describing?

**Comment by erichonkanen** [comment]
ok but the problem is I only want to display this at the very beginning of the entire result set... I need to both a) ensure im at index 0, and b) ensure im at the very beginning of the results (meaning there are no more results to load // paginated data)

**Comment by erichonkanen** [comment]
maybe there is a way I can set a css class and do it that way? not sure

**Comment by pzuraq** [comment]
Well, this would render at the very top of the collection, so it would not be visible unless you were at index 0. You could then use an if statement for if there is more data to be loaded:

```
<div class="scroll-container">
  {{#if noMoreData}}
    <h1>Yay we are at the very beginning!</h1>
  {{/if}}
  {{#vertical-collection items as |item index|}}
    ...
  {{/vertical-collection}}
</div>
```

The one difference here is that as soon as you load the first record, the text would always be _rendered_. However, because it's at the top of the scroll container, above all of the occluded content and above the vertical collection, it will not be _visible_ until the user scrolls to index 0. Does that work?

**Comment by pzuraq** [comment]
We talked about this on Slack and the solution above does work, so closing this for now.
