### ISSUE TITLE
Remove scroll handlers can be called before they are added

### ISSUE THREAD

**Issue by nragaz** [html-next/vertical-collection#139]
If teardown occurs before the first scheduled sync, then `removeScrollHandler` will error because the scroll handler hasn't been installed yet.

This can happen if a user navigates away from the page that displays the component at precisely the moment between init and sync.

**Comment by ming-codes** [comment]
I had a similar issue, but I thought it was because of `setTimeout` not hooked up with run loop. It may be this issue.

**Comment by pzuraq** [comment]
Ah, it does look like this is the same issue from before. We should definitely wrap that code in `willDestroy` with a conditional based on whether or not initialization has happened, thanks for pointing this out!

**Comment by nragaz** [comment]
@ming-codes  Thanks for the quick fix!
