### ISSUE TITLE
Cookbook Recipes

### ISSUE THREAD

**Issue by pzuraq** [html-next/vertical-collection#159]
Tracking the list of recipes we need to add to the cookbook to show users ways to use VC in their apps/libraries.

### Performance

- [ ] Proxying for transient state (storing component state for occluded items, like in ember-table)

### A11y

- [ ] Dynamically loading more content in an accessible way (from @melsumner "Replace automatic infinite scrolling with a “Load more results…” button or link that explicitly invites the user to add more. Once they do a few times, prompt them to ask if they’d like to turn auto-loading of more results on.")

**Comment by mixonic** [comment]
I'm going to close this as stale :beers:
