### ISSUE TITLE
Consider renaming Container to something else

### ISSUE THREAD

**Issue by ming-codes** [html-next/vertical-collection#163]
The name `Container` clashes with Ember's internal injection container. This makes debugging memory leaks more difficult as the heap snapshot does not distinguish between the two.

**Comment by pzuraq** [comment]
I think that’s a reasonable change, the current name is a little abitrary. Can work on in a few weeks once I’m back from vacation

**Comment by ming-codes** [comment]
Awesome! Thanks!
