### ISSUE TITLE
TypeError: null is not an object (evaluating 'this.skipList.prepend')

### ISSUE THREAD

**Issue by kylemellander** [html-next/vertical-collection#187]
When using vertical-collection, I often get this error:
```
TypeError: null is not an object (evaluating 'this.skipList.prepend')
```

**Comment by pzuraq** [comment]
Are you on the latest version of vertical-collection? beta.10? We merged a fix for this issue recently, strange that it's popping up again

**Comment by kylemellander** [comment]
I just realized I was not on that! Sorry, I will upgrade
