### ISSUE TITLE
Missing scrollbars - iel11 and edge

### ISSUE THREAD

**Issue by maxwondercorn** [html-next/vertical-collection#199]
I don't necessarily know if this is a vertical-collection issue directly but ember-light-table uses vertical-collection for it's occlusion rendering feature.  On IE11 and Edge the scrollbar doesn't show up when occlusion is enabled.

The vertical-collection examples on the demo page work fine on IE11 and Edge.  I have opened an issue on the ELT repo but I'm trying to do a little debugging on my own.

I do have 'includePolyfill: true` defined in ember-cli-build to take of issue in #74.

**Comment by buschtoens** [comment]
I would _assume_, that this is an issue with ELT, but I don't have access to an IE11 browser right now to verify this. I'll try to get my hands on a Windows machine today.

Referencing https://github.com/offirgolan/ember-light-table/issues/553

**Comment by maxwondercorn** [comment]
I finally got around to digging into this problem and found 

`-ms-overflow-style: none;`

buried in one of my sass stylesheets.  This has no affect on non-occluded tables in IE and Edge but defintelty breaks occluded tables. I have not checked this against a vertical-collection to see if it breaks anything

**Comment by pzuraq** [comment]
This seems to be a styling issue unrelated to VC. The `-ms-overflow-style` property styles scrollbars, so it's likely hiding the scrollbar in those browsers.
