### ISSUE TITLE
Scroll not working properly in firefox (latest)

### ISSUE THREAD

**Issue by erichonkanen** [html-next/vertical-collection#214]
Opening issue so we can track it, 

In firefox (Im on 61.0.1), when scrolling up in a VC such as below, the scroll movement instantly stops and the user must reinitiate the scroll. This leads to a "jumpy" or jagged scroll behavior that breaks the user experience. Seems to also happen on ios.
```
    {{#vertical-collection
        bufferSize=15
        estimateHeight=50
        firstVisibleChanged=(action 'firstVisibleChanged')
        items=items
        renderFromLast=true
        shouldRecycle=true
        staticHeight=false
        as |item index|
    }}
```

Ember: 3.0.0
Vertical-Collection: `master branch`
FireFox: 61.0.1

**Comment by pzuraq** [comment]
We've opened up a bug report with Firefox about this behavior, since it seems to be non-standard: https://bugzilla.mozilla.org/show_bug.cgi?id=1474196
