### ISSUE TITLE
IE11 issues

### ISSUE THREAD

**Issue by amk221** [html-next/vertical-collection#227]
There are a couple of oddities here, reported by users of our app

1. When selecting text, the occluded-content element shows up.
2. The counts are wrong (In the below screenshot, only 9 are visible, but there should be 10)
    so one is being occluded unncessarily

![screen shot 2018-08-30 at 17 35 58](https://user-images.githubusercontent.com/382061/44865784-32522800-ac7b-11e8-87e9-1279a89fa570.png)

**Comment by amk221** [comment]
I did a quick sanity check in a fresh ember app, with the following code:

```handlebars
<table>
  {{#vertical-collection this.model
    containerSelector="body"
    tagName="tbody"
    estimateHeight=100
    staticHeight=true
    bufferSize=0
    as |item index|}}
    {{log item index}}
    <tr>
      <td>{{index}}</td>
      <td>{{item.name}}</td>
    </tr>
  {{/vertical-collection}}
</table>
```

And it worked with Ember 2.12.2 and vertical collection 1.0.0-beta.7 as per the demo site.
But, it didn't work after bumping Ember to 3x.

Continuing to debug...

**Comment by amk221** [comment]
It seems to be something with `tagName="tbody"`

**Comment by brandontksmith** [comment]
It appears this is happening in Edge too...

**Comment by robgraeber** [comment]
FWIW it works fine for me with Ember 3.3, maybe it's related to using it with tables.

**Comment by brandontksmith** [comment]
I'm running on Ember 3.4.x, but I am using it with tables.

**Comment by pzuraq** [comment]
Just wantod to say that this definitely appears to be a real issue, but I unfortunately haven't had time to dive in and figure it out. Hopefully will have some time in the coming months, currently all my focus has been on the native class story in Ember and Ember Octane in general.

VC is still on my radar, and I plan to come back to it as soon as I have some time.

**Comment by miketervela** [comment]
When you only get two rows rendered, does forcing a redraw - for instance, by changing the size of the browser - get you the other visible rows?  We found  making sure every div had a height from table to app-body fixed that

**Comment by artikhurana** [comment]
I'm facing the same issue on IE. Is there any fix provided for this issue?

**Comment by Emerson** [comment]
Some of our customers are seeing this in Chrome

**Comment by mixonic** [comment]
IE support ended with the 1.x series FYI (per https://github.com/html-next/vertical-collection/pull/321). Do not expect maintainers to look into IE11 issues.
