### ISSUE TITLE
Can't reliably test `vertical-collection` due to scheduling of updates

### ISSUE THREAD

**Issue by EWhite613** [html-next/vertical-collection#231]
When testing `vertical-collection` with scenarios where the `items` passed are updated, a user can't reliably test the updated item. Since scheduled task to update the item in the virtual component isn't tied to `'ember-test-helpers`'s `wait`.

It gets to https://github.com/html-next/vertical-collection/blob/master/addon/-private/data-view/radar/radar.js#L229 but the `wait` will not wait for `update` to be run. So by the time you're doing assertions, `this._didUpdateItems` will still be `true` (Ie item visible in the list isn't updated yet)

**Comment by pzuraq** [comment]
Make sure you register the test waiter: https://github.com/html-next/vertical-collection/blob/master/tests/test-helper.js#L2

**Comment by EWhite613** [comment]
Well, that works. That should probably be documented somewhere

**Comment by pzuraq** [comment]
Documentation is the top item remaining on the [v1.0.0 roadmap](https://github.com/html-next/vertical-collection/issues/1)! Unfortunately I don't have time to push it forward at the moment, but PRs are definitely welcome

**Comment by oskarrough** [comment]
Hi, is this fix also meant for apps using the addon?

```
assert.equal(this.$('li').length, 3)
```

I'm testing a component using {{vertical-collection}} and the items aren't reliable there in the DOM at the time of the assertion. Is there a way to wait for vertical-collection to render in a test?
