### ISSUE TITLE
Use of deprecated `sendAction()`

### ISSUE THREAD

**Issue by fpauser** [html-next/vertical-collection#243]
This warning pops up when using vertical-collection:

DEPRECATION: You called sendAction("lastVisibleChanged") but Component#sendAction is deprecated. Please use closure actions instead. [deprecation id: ember-component.send-action] See https://emberjs.com/deprecations/v3.x#toc_ember-component-send-action for more details.

Env:
```
$ ember -v
ember-cli: 3.5.0
node: 8.11.3
os: linux x64
```

Using 1.0.0-beta.12 of html-next/vertical-collection.

**Comment by fpauser** [comment]
Fixed by #244.

**Comment by rwwagner90** [comment]
Fixed by #233
