### ISSUE TITLE
staticHeight=true renders no items when direct parent is not the scrollable container

### ISSUE THREAD

**Issue by billdami** [html-next/vertical-collection#252]
(I'm still working on getting an ember-twiddle up to demonstrate this, but ember-twiddle currently seems to not want to allow the `@html-next/vertical-collection` to be installed...)

Essentially, when the `staticHeight=true` argument is set, and the `{{vertical-collection}}` is in a scrollable element (not `<body>`), but is NOT a direct child of the scrollable element (for example, is nested in a component template that is rendered in the scrollable parent), on initial render the list is completely blank. However, the scroll height is correct (i.e. the `<occluded-content>` element is rendered w/the correct height), and as soon as you either click somewhere on the vertical-collection, or resize the window, the list re-renders, and renders the items correctly.

With `staticHeight=false` this issue does not occur at all, and the list is displayed correctly on initial render.

**Comment by mixonic** [comment]
I believe the direct parent should be the scrollable container. `staticHeight=true` opts vertical collection into an optimistic mode for layout of contents, and having other content in the scrollable area may conflict with those assumption.

I'm going to close this as an supported use case. I can imagine there is documentation that can be improved for this case though, or even implementation to add support given it was tested and shown to be generically useful in test case.
