### ISSUE TITLE
[BETA.14] "Must provide estimateHeight value" when using angle bracket invocation

### ISSUE THREAD

**Issue by erichonkanen** [html-next/vertical-collection#284]
When using angle bracket invocation I am receiving an error saying "Must provide estimateHeight value" despite having provided it.
```
  <VerticalCollection
    bufferSize={{this.VC_BUFFER_SIZE}}
    estimateHeight={{this.VC_HEIGHT}}
    items={{this.posts}}
    shouldRecycle={{this.VC_SHOULD_RECYCLE}}
    staticHeight={{this.VC_STATIC_HEIGHT}}
    as |post|
  >
    <span>
      aaa{{post.id}}
    </span>
  </VerticalCollection>
```
```

  VC_BUFFER_SIZE = 15;
  VC_HEIGHT = 50;
  VC_SHOULD_RECYCLE = true;
  VC_STATIC_HEIGHT = false;

```
![image](https://user-images.githubusercontent.com/230757/62505201-6fd70380-b7b0-11e9-9b11-fb3e7d9feb5e.png)

Changing back to curly brackets resolves the problem.

**Comment by scottkidder** [comment]
@erichonkanen You need to prepend your component arguments with `@` because without it they are being passed as attributes. I'm working through this stuff right now too.

https://guides.emberjs.com/release/reference/#toc_angle-bracket-syntax

**Comment by erichonkanen** [comment]
duh that was it! :D thanks
