### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by amk221** [html-next/vertical-collection#288]
I'm the process of upgrading my addons. `yarn outdated` suggests I can upgrade vertical-collection from `1.0.0-beta.13` to `1.0.0`

But there are no details in the changelog or on the releases page.

Would be great to get some details, ty!

**Comment by rwwagner90** [comment]
@amk221 not really any changes, just shipping what you were using in the betas as a major version

**Comment by amk221** [comment]
Ok, thank you! I figured that would be all. (Still nice to have the go-to places have the up to date info)

**Comment by rwwagner90** [comment]
Totally agree. We need to start generating changelogs with each release.
