### ISSUE TITLE
TypeError: Class constructor Promise cannot be invoked without 'new'

### ISSUE THREAD

**Issue by fran-worley** [html-next/vertical-collection#290]
Noticed this is causing our beta builds to fail in Ember Light Table and have traced it back to here as you've got the same failures error https://travis-ci.org/html-next/vertical-collection/jobs/572854662

Any ideas where it's coming from?

**Comment by rwwagner90** [comment]
@fran-worley lots of things are broken because of this right now. It was a bug in Ember, which has been fixed but not released yet. https://github.com/emberjs/ember.js/pull/18281
