### ISSUE TITLE
Noticeable lag between rendering and actions being sent

### ISSUE THREAD

**Issue by pzuraq** [html-next/vertical-collection#31]
ping @antidis

[See previous conversation on this commit](https://github.com/html-next/vertical-collection/commit/4290749605cda2631eaa6e1450e5d56a5aef5718)

It seems that using `run.next` to schedule actions causes the actions to lag a little bit before being sent. The lag is noticeable, @antidis I'm assuming that scrolling are the pattern between 3400ms and 4200ms and the actions are sent at 4800ms?

<img width="1323" alt="screen shot 2017-04-11 at 19 00 15" src="https://cloud.githubusercontent.com/assets/11009/24923819/aaba8000-1eea-11e7-998b-542c6650df99.png">

What version of Ember are you using currently?

**Comment by antidis** [comment]
To be specific:

* Scrolling to the end of the currently-loaded content takes place first.
* I hit the end and nothing seems to happen. I can scroll back up fine—the browser has not locked.
* Loading kicks in a short time later (the loading function in this case is just a task that throws a few hashes into the `rows` array, then notifies Ember of the change).

It's hard to get the timings precise as it's hard to map my inputs precisely to the timeline above, and the browser window with the above timeline has been lost. When I generated a profile a while ago, it appears to show a ton of time spent idling but not much else.

This behaviour vanishes when `run.next` is replaced with `run.schedule('afterRender', ...` here: https://github.com/html-next/vertical-collection/commit/4290749605cda2631eaa6e1450e5d56a5aef5718#diff-dd82fd2ab5100320f9dd5248149349efR312 - but as Chris mentions, this isn't a fix.

I had hoped to get some more information to help my own digging into the situation—we're not quite at the stage where I have a twiddle to show the behaviour, but I'll try create on tomorrow.

We're on Ember 2.11.3.

**Comment by pzuraq** [comment]
Interesting. Yeah, it's weird that the browser is spending so much time doing nothing, `run.next` should just schedule a new runloop in a `setTimeout` which would generally run in between scrolls/RAFs. Not sure why it's being pushed out that much, but that's definitely way too much of a delay. @runspired and insights on this?

@antidis could you possibly paste the template usage and the actions that caused this so we can try to debug? Or if you could make an `ember-twiddle` or branch on the dummy app that demonstrates the issue that would be ideal

**Comment by antidis** [comment]
Working on the twiddle this morning. Will post then.

**Comment by antidis** [comment]
Here's a stripped-down and sanitised version of the addon we're hoping to include `vertical-collection` in:

https://github.com/antidis/vertical-collection-bug-demo

The problem still occurs, and occurs reliably. Interestingly, **this problem does not occur in Firefox.** A colleague suggested that this may indicate an RSVP bug.

**Comment by antidis** [comment]
The problem also does not occur in Safari. This may be hitting a Chrome bug.

**Comment by pzuraq** [comment]
Weird, I'm not able to reproduce locally:

![apr-12-2017 11-59-15](https://cloud.githubusercontent.com/assets/685518/24974578/7fdca6e6-1f77-11e7-9567-28a5b4f390e7.gif)

There isn't really a noticeable gap between when the RAF ends and the scroll event fires. If the loading event were a longer running async task then there could be lag, definitely, but that's not really something we can control.

Maybe there's a hardware component to this as well?

**Comment by antidis** [comment]
I sure hope not.

This is on a mid 2015 Retina MBP. Chrome version: 57.0.2987.133 (64-bit). Happens in HiDPI and non-HiDPI resolutions too. We have other test hardware available, but so far we've only tested it on (likely 2015) MBPs.

What hardware are you running? If we find out, we can hopefully track it down.

**Comment by pzuraq** [comment]
I'm running El Capitan on a 2013 rMBP, Chrome Version 57.0.2987.133 (64-bit)

Any chance you could take a video of it in action? I'll try to reproduce locally but I can't really help until I do 😅

**Comment by antidis** [comment]
![scrolling-problem](https://cloud.githubusercontent.com/assets/11009/24978167/976b154a-1fc7-11e7-9404-77115598eb99.gif)

**Comment by pzuraq** [comment]
Ok yeah, super noticeable and nothing like what's happening on my machine. WEIRD.

Definitely a priority to get this fixed before 1.0.0, even if it's not an issue in this library directly.

**Comment by pzuraq** [comment]
@antidis could you possibly send a couple of timeline screenshots with these sections zoomed in?

<img width="1323" alt="aaba8000-1eea-11e7-998b-542c6650df99_copy" src="https://cloud.githubusercontent.com/assets/685518/24980011/4191f1d4-1f8b-11e7-83c3-53c4f061e045.png">

Would help to get a better look at what's going on at those points in time. Also, I'm up for remote debugging via Screenhero or something like that if you can do that.

**Comment by GavinJoyce** [comment]
> Maybe there's a hardware component to this as well?

I can reproduce this issue on my machine in both `Chrome 57.0.2987.133 (64-bit)` and `Chrome  59.0.3069.0 canary (64-bit)` with no addons on `MacBook Pro (Retina, 13-inch, Early 2015)` running `OSX 10.12.4 (16E195)`

**Comment by antidis** [comment]
I'll try do something like that tomorrow. I suspect you're on SF time, and I'm in Dublin, so it may be tricky to arrange remote debugging. @gavinjoyce maybe we can pair on this tomorrow afternoon?

**Comment by runspired** [comment]
Chrome aggressively throttles and can sometimes even drop `setTimeout` calls during scroll.  This seems overly aggressively throttled though.

As I think about this, we may *have* to move to `afterRender` scheduling for the microtask semantics to avoid this.

One thing to note, with scroll, it is never guaranteed that you'll be given the chance to respond in a reasonable amount of time.  Bot unique to Chrome, but Chrome has always been more aggressive in this area.

**Comment by pzuraq** [comment]
Makes sense, we can move the scheduling to `afterRender` and add a note in the Perf section in the docs (which needs to be added). As long as actions are short and simple, or schedule things asynchronously themselves, it should be fine.

**Comment by pzuraq** [comment]
Merged the change, let me know if you're still having issues @antidis @GavinJoyce!

**Comment by antidis** [comment]
@pzuraq Testing it locally, and the problem seems to have disappeared. Thanks!
