### ISSUE TITLE
Tests fail sporadically

### ISSUE THREAD

**Issue by pzuraq** [html-next/vertical-collection#33]
Tests are failing fairly regularly on Travis. I have a feeling it's a subtle issue we're not capturing, but it's hard to say.

Add logs for failures to this issue.

**Comment by pzuraq** [comment]
[log-b34fd15-ember-default.txt](https://github.com/html-next/vertical-collection/files/920632/log-b34fd15-ember-default.txt)

**Comment by pzuraq** [comment]
Still happens on occasion, much less frequent now. Seems to be before the build actually starts so could be NPM/Bower related.

**Comment by runspired** [comment]
@pzuraq looking at the error in the logs, it seems to be due to #52, closing in favor of that ticket.
