### ISSUE TITLE
iframe gets loaded twice in vertical-collection with shouldRecycle=false

### ISSUE THREAD

**Issue by bobbajs** [html-next/vertical-collection#338]
When using vertical-collection with item that has iFrame in it, the iframe `onLoad` event is fired twice:

hbs:
```
{{#vertical-collection items
    staticHeight=false
    shouldRecycle=false as | item |}}
    <iframe onload={{action "onLoad"}}
{{/vertical-collection}}
```

js: 
```
actions: {
     onLoad() {
         console.log('iframe onLoad is fired');
      }
}
```

With only 1 item, console output will display `iframe onload is fired` twice. Is anyone seeing the same issue?

**Comment by mixonic** [comment]
I'm going to close this as stale. I guess I find this mildly surprising, but vertical-collection is probably built with the assumption that DOM manipulation is free from side-effects, and `iframe` will definitely break that assumption (as would web components!)

Feel free to re-open if you have discovered there is something critical here, or perhaps this issue highlights an opportunity for better documentation and examples.
