### ISSUE TITLE
Not compatible with ember-4.0.0

### ISSUE THREAD

**Issue by fpauser** [html-next/vertical-collection#339]
Right after adding it to my project (ember-4.0.0) without actual usage of `<VerticalCollection>`:
```
Uncaught ReferenceError: Ember is not defined
```

**Comment by NullVoxPopuli** [comment]
@mixonic thoughts on this?
would you accept a PR to fix?

**Comment by mixonic** [comment]
There is a 3.0.0-0 release which is compatible with ember 4. See https://github.com/html-next/vertical-collection/tree/v3.0.0-0

**Comment by NullVoxPopuli** [comment]
awesome, thanks!!! <3

**Comment by pjcarly** [comment]
Cheers!

**Comment by mixonic** [comment]
Resolved in 3.0.0 :tada:
