### ISSUE TITLE
v3 Proposal

### ISSUE THREAD

**Issue by mixonic** [html-next/vertical-collection#341]
In alignment with https://github.com/Addepar/ember-table/pull/919 (ember-table is one of the main consumers of vertical collection), I propose a v3 major release of vertical collection.

The main breaking change is: Remove support for Ember < 2.18 and ensure compatibility with Ember 4.

Thoughts?

**Comment by mixonic** [comment]
The PR at https://github.com/html-next/vertical-collection/pull/343 tracks a prerelease branch. CI is set up, and I'll look to extract whatever minimal changes from https://github.com/html-next/vertical-collection/pull/335 that I can get it green.

I've also pinned the minimum Node version at 14.

**Comment by mixonic** [comment]
`3.0.0-0` has been released, and a `release-2` branch for legacy v2 support has been created.

Downstream in Ember Table I've created https://github.com/Addepar/ember-table/pull/921 as a smoke test, though it doesn't run tests against Ember 4 at this point.

Please try the pre-release if applicable, and provide feedback!

**Comment by runspired** [comment]
@mixonic I think we forgot to actually publish the v3

**Comment by mixonic** [comment]
@runspired my plan was to wait until ember-table gets a stable release well tested via integration into real apps before cutting a stable here.

**Comment by bakerac4** [comment]
Can this release be cut now at this point? Or are we still waiting for results from ember-table?

**Comment by mixonic** [comment]
I've been trying to get the last beta of ember-table successfully landed into a large app at Addepar. We're seeing unexpected width changes in cells. At first it seemed to be from the 3.0.0-0 to 3.0.0-1 changes, however I believe that analysis might have been in error and I'm debugging.

I suspect we're in the clear on the vertical collection from, though my confidence is only 80%. I'll be able to allocate some time over the next two days to try and get the style change isolated or rationalized so we can ship.

**Comment by mixonic** [comment]
3.0.0 was released in early May. The issues we had been encountering with unexpected layout changed were related to a CSS bug fixed in 2.0.1 which hadn't been adopted into that codebase.

Closing this. Onward to 4.0!
