### ISSUE TITLE
Components not rendering

### ISSUE THREAD

**Issue by pzuraq** [html-next/vertical-collection#35]
@erkarl is experiencing an issue where components seem to not render correctly at all: 

![image](https://cloud.githubusercontent.com/assets/685518/24985102/e2190c94-1fa6-11e7-986a-5a01511f3a66.png)

The associated code is:

```
{{#vertical-collection
  content=jobs
  key='@index'
  containerSelector="body"
  defaultHeight=125
  as |job index|
}}
  {{job-item job=job}}
{{/vertical-collection}}
```

The project is [open source](https://github.com/erkarl/fronthat/pull/18) so we can debug directly.

**Comment by pzuraq** [comment]
Should be fixed now, @erkarl can you confirm?

**Comment by erkarl** [comment]
Yep, working on latest master. @pzuraq - thanks. :)
