### ISSUE TITLE
padding on the container and renderFromLast

### ISSUE THREAD

**Issue by evoactivity** [html-next/vertical-collection#37]
So my scroll container has padding on it, and I want to load scrolled to the bottom so I've set `renderFromLast` to true, this seems to work except the scroll position doesn't seem to take into account the container top and bottom padding.

I can work around this in my app with different css but I wonder if this should be handled by the library?

**Comment by pzuraq** [comment]
Hmm, that's a tricky one. Users can technically put any number of things before or after the `vertical-collection` component, like headers, footers, or other things. Theoretically it's supposed to be a drop-in replacement for `each`, so you should be able to use it like an each and expect it to flow with the rest of the document correctly. So I'm not sure what the more intuitive behavior would be here.

One possible solution would be to set the initial `scrollPosition` value to some absurdly large number, but I don't know if that's any better.

**Comment by pzuraq** [comment]
Quick update, `scrollPosition` is definitely not recommended, we're removing it for `beta.2`.

@runspired any thoughts here? If `idForFirstItem` is not provided it does kind of make sense to have `renderFromLast` render from the bottom of the `scrollContainer` rather than the last element. I could see it going either way.

**Comment by runspired** [comment]
I need more context on this issue, as I understand it, is the layout this?

```
<scroll-container>
   <some-header />
   <vertical-collection />
   <some-footer />
</scroll-container>
```

**Comment by evoactivity** [comment]
@runspired 

my instance is more like so

```
<some-header />
<scroll-container>
   <vertical-collection />
</scroll-container>
<some-footer />
```

Then to keep my collection items from being flush I added padding to the scroll container. So let's say my padding was 20px all around, the `renderFromLast` would goto the right item but be 40px too short.

**Comment by runspired** [comment]
@evoactivity can you use margin instead for this? The trouble with padding is it's relatively hard to distinguish between height and padding, but it's not too hard to distinguish between margin and (height + padding).

**Comment by runspired** [comment]
@evoactivity this should be fixed for static heights on master, and for dynamic heights when #84 lands.

**Comment by runspired** [comment]
@evoactivity this should be fixed now, closing unless you encounter additional issue :)

**Comment by evoactivity** [comment]
Nice one @runspired, I'll let you know if I run into anything?
