### ISSUE TITLE
Can't get a basic sample

### ISSUE THREAD

**Issue by alexander-alvarez** [html-next/vertical-collection#49]
Wanted to play around and test, but I can't even get a basic sample up and running.

see https://github.com/alexander-alvarez/vertical-collection-test/commit/925638daf641610c78ef76c5c4995765f1d1f4de

any ideas as to what I'm doing wrong?

**Comment by pzuraq** [comment]
Hey @alexander-alvarez! It looks like you need to add some styles to the scroll container. `vertical-collection` does not make any assumptions about how you want to style your app, and will not apply any styles anywhere.

You'll want to add something like this to your `app.css`:

```
.scrollable {
  overflow-y: scroll;
}
```

**Comment by pzuraq** [comment]
Let me know if you have any more issues, always glad to help. I think we should get this particular issue into the docs, I think it'll probably come up pretty frequently with new users.

**Comment by alexander-alvarez** [comment]
... sorry. late night != conducive to logical thinking...
once vertical collection is published and 1.0, I can throw a base twiddle together that can be used to demo, and serve as a base to demonstrate bugs / setup issues.

**Comment by pzuraq** [comment]
No worries, happens to all of us!

A twiddle for debugging would be awesome, that would really help for debugging and such. Wouls definitely appreciate it 😄
