### ISSUE TITLE
`index` is not passed into the component on initial render

### ISSUE THREAD

**Issue by pzuraq** [html-next/vertical-collection#53]
we pass the correct item, but not `index`. This should be added here: https://github.com/html-next/vertical-collection/blob/master/addon/-private/data-view/radar/radar.js#L276

**Comment by runspired** [comment]
@pzuraq was there a perf reason why initially you didn't pass this in? I feel I semi-remember you trying to get around broadcasting index if unneeded for perfs.

**Comment by runspired** [comment]
Fixed.
