### ISSUE TITLE
Possible bug in Firefox, scrollContainer too high

### ISSUE THREAD

**Issue by pzuraq** [html-next/vertical-collection#54]
The FrontHAT app seems to have too much space at the end of the scroll container, specifically in Firefox

<img width="1680" alt="screen shot 2017-04-25 at 18 04 19" src="https://cloud.githubusercontent.com/assets/685518/25397827/95878b1a-299e-11e7-8ecb-7c63d6134b8f.png">

**Comment by runspired** [comment]
Any more details? This seems more likely to be a CSS issue on their end.

**Comment by pzuraq** [comment]
Yeah, not us. Turns out it's weird behavior with margins and box shadows in Firefox.
