### ISSUE TITLE
Can't scroll to bottom on dbMon example in Chrome

### ISSUE THREAD

**Issue by v3ss0n** [html-next/vertical-collection#57]
When scrolled down to the bottom-most , scroll stuck , can't get go the bottom.
![screenshot_20170426_181913](https://cloud.githubusercontent.com/assets/419606/25433017/e16220ea-2aac-11e7-8eba-6b896ef810b2.png)

**Comment by pzuraq** [comment]
https://html-next.github.io/vertical-collection/#/examples/dbmon

**Comment by pzuraq** [comment]
Found the issue and will be working on a patch

**Comment by runspired** [comment]
The issue here appears to be an optimization we made for when the entire array appears to have been emptied or swapped, that resets scroll to the top.  Tracking a stable key for first/last reached should be enough.
