### ISSUE TITLE
Item height must always be above minimum value

### ISSUE THREAD

**Issue by bloodknight2010** [html-next/vertical-collection#61]
I installed ember @html-next/vertical-collection and used vertical collection. When I switch mobile view and web view in browser. I got the following error.
**_Item height must always be above minimum value_**
Pls help me.

**Comment by runspired** [comment]
It means exactly what it says, `defaultHeight` is a minimum value to which you agree that all your items are "at least as tall as", when an item height is encountered that is less than the default height in dev mode, you get this error.
