### ISSUE TITLE
master currently failing all tests

### ISSUE THREAD

**Issue by antidis** [html-next/vertical-collection#64]
Seems to have happened as a result of this PR: https://github.com/html-next/vertical-collection/pull/62

Build is here: https://travis-ci.org/html-next/vertical-collection/builds/226719240

Unlike other broken builds, this failure happens consistently across all ember versions tested.

cc @runspired

**Comment by runspired** [comment]
@antidis odd, this passed everything locally for me, lemme recheck

**Comment by runspired** [comment]
@antidis are you in the EC slack?

**Comment by antidis** [comment]
Just joined. "davebarrett" there.
