### ISSUE TITLE
Handle the collection starting hidden and off-screen

### ISSUE THREAD

**Issue by runspired** [html-next/vertical-collection#69]
See: https://github.com/runspired/smoke-and-mirrors/issues/95
See: https://github.com/runspired/smoke-and-mirrors/issues/150
And: https://github.com/runspired/smoke-and-mirrors/pull/151

Confirmation that this is still a problem in 1.0 beta 3: https://github.com/runspired/smoke-and-mirrors/pull/151#issuecomment-298159870

**Comment by pzuraq** [comment]
We should test if this is still an issue now with the `estimateHeight` refactor. VCs will only render as needed, so if the collections starts hidden/offscreen and comes on, they should populate it automatically.
