### ISSUE TITLE
Unknown plugin "transform-es2015-block-scoping"

### ISSUE THREAD

**Issue by tiandavis** [html-next/vertical-collection#73]
Heads up folks! We're getting this error after `ember install @html-next/vertical-collection`.

```
ReferenceError: Unknown plugin "transform-es2015-block-scoping" specified in "base" at 0, attempted to resolve relative to "modules/vertical-collection/-debug/edge-visualization"
```

Thoughts?

```
ember -v

ember-cli: 2.9.1
node: 4.2.6
os: darwin x64
```

Thanks Folks!

**Comment by runspired** [comment]
@tiandavis this likely means you need to update ember-cli for using babel6

**Comment by pzuraq** [comment]
@tiandavis just to follow up on this, I have a clean Ember app generated from ember-cli 2.9.1, ran `ember install @html-next/vertical-collection` and everything appears to be working. Is the issue still there for you?
