### ISSUE TITLE
Issues with race conditions and table crashing when browser resizes up

### ISSUE THREAD

**Issue by maxzats** [html-next/vertical-collection#87]
<img width="646" alt="screen shot 2017-05-09 at 11 13 39 pm" src="https://cloud.githubusercontent.com/assets/4649160/25912556/8be67510-356c-11e7-8891-ca41b2057694.png">
<img width="1807" alt="screen shot 2017-05-09 at 10 28 03 pm" src="https://cloud.githubusercontent.com/assets/4649160/25912558/8c053efa-356c-11e7-9f88-909633d62a88.png">
<img width="1599" alt="screen shot 2017-05-09 at 9 22 51 pm" src="https://cloud.githubusercontent.com/assets/4649160/25912557/8bfbf110-356c-11e7-8139-0ea340f4553a.png">

**Comment by runspired** [comment]
@maxzats Thanks :) cc @pzuraq

**Comment by pzuraq** [comment]
Should be solved by #89
