### ISSUE TITLE
Should use `max-height` property of scrollContainer if it exists

### ISSUE THREAD

**Issue by pzuraq** [html-next/vertical-collection#88]
`max-height` is a valid way to define the bounds of a scrollContainer, so it makes sense to use that if it exists.

**Comment by cibernox** [comment]
I was about to open the same issue, as I need it for https://github.com/cibernox/ember-power-select-collection

I understand that this refers to reading it from the computed styles of the container, not making it part of the component's API.

**Comment by pzuraq** [comment]
Yes, we would be reading the CSS of the scrollContainer and if it has a `max-height` we would use that, otherwise we would use the calculated height. This should be coming in the next week, I'm starting work on some refactors that'll help with initial rendering speed, so it'll probably happen in there

**Comment by cibernox** [comment]
@pzuraq If you give me some guidance I might be try. I've seen that the component uses minHeight all over the place, but I'm a bit lost between the container and the `getDimensions` helper.

**Comment by cibernox** [comment]
If this is one of those "better stay away, it's not as simple as it seems" thing, let me know.

**Comment by pzuraq** [comment]
It's not too hard to add right now, but the refactoe I'm about to land will change the flow it gets set in pretty significantly for perf reasons. Shoukd be able to land it my Monday at the latest, so probably best to wait

**Comment by pzuraq** [comment]
Ok, this issue should be fixed by #89. Let us know if it works for you @cibernox!
