### ISSUE TITLE
Weird padding/margin on occluded-content

### ISSUE THREAD

**Issue by erkarl** [html-next/vertical-collection#91]
The landscape mode has way too much “padding/margin” when scrolling (on occluded content).
 
https://drive.google.com/file/d/0B4OTX4eSH_Plb0ExY25TdVc5eXc/view

Also tested it on real devices (iOS 10 Chrome which is just a Safari wrapper) and it seems a legit bug.

Source: https://github.com/erkarl/fronthat/blob/master/app/components/job-list/component.js
Live demo: https://fronthat.com/

**Comment by erkarl** [comment]
Also tried replicating the issue using vertical-collection examples, but no dice.

**Comment by pzuraq** [comment]
This issue appears to be fixed on the latest master, cloned and ran it locally. I believe we caught this issue in a recent refactor and have tests for it now, so hopefully it won't pop up again.

**Comment by erkarl** [comment]
@pzuraq I was able to reproduce it again on latest master.
`rm -Rf node_modules tmp dist` -> `yarn`

![screen shot 2017-05-25 at 16 56 36](https://cloud.githubusercontent.com/assets/1056569/26453088/31bd50da-416b-11e7-8ade-27ef42faee29.png)

**Comment by pzuraq** [comment]
You need to run yarn upgrade, remember that Yarn will lock you to specific commit.

**Comment by erkarl** [comment]
Right, thanks @pzuraq. Working perfectly (tested on real devices). Even Samsung Galaxy S3 Mini is usable.

**Comment by pzuraq** [comment]
Awesome, great to hear! I want to get a lower end device to test on, glad it's performant even on smaller devices 😄
